name: dami_ephys
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - pypots
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
